export const users = [
  {
    _id: '66047819dc5ef89f9526a2b5',
    index: 0,
    guid: 'f0b1fe1c-8082-4bd7-ac1f-58f5f9636199',
    isActive: false,
    balance: '$2,183.01',
    picture: 'http://placehold.it/32x32',
    age: 36,
    eyeColor: 'blue',
    name: 'Shaffer Clark',
    gender: 'male',
    company: 'TSUNAMIA',
    email: 'shafferclark@tsunamia.com',
    phone: '+1 (824) 597-3551',
    address: '124 Williams Court, Waiohinu, Colorado, 7656',
    about:
      'Minim dolore proident magna minim cupidatat sit duis amet laborum eu. Nisi laboris minim sit nisi et duis ad labore consectetur cupidatat tempor. Sit veniam tempor commodo occaecat exercitation aute adipisicing culpa qui sit et dolor elit. Ex pariatur est non nostrud adipisicing commodo ex velit duis do irure nisi. Aliqua fugiat qui eiusmod in et ex ea amet incididunt deserunt.\r\n',
    registered: '2014-07-28T01:49:21 -06:00',
    latitude: 81.918156,
    longitude: 39.677613,
    tags: ['sit', 'aliquip', 'ex', 'ullamco', 'eu', 'et', 'cillum'],
    friends: [
      {
        id: 0,
        name: 'Osborn Everett',
      },
      {
        id: 1,
        name: 'Hazel Suarez',
      },
      {
        id: 2,
        name: 'Aimee Nieves',
      },
    ],
    greeting: 'Hello, Shaffer Clark! You have 5 unread messages.',
    favoriteFruit: 'banana',
  },
  {
    _id: '66047819baca23c196f4e8d0',
    index: 1,
    guid: '595cffae-94af-4fae-a97f-b81537975a5a',
    isActive: false,
    balance: '$2,953.82',
    picture: 'http://placehold.it/32x32',
    age: 20,
    eyeColor: 'green',
    name: 'Drake Stanley',
    gender: 'male',
    company: 'FLYBOYZ',
    email: 'drakestanley@flyboyz.com',
    phone: '+1 (857) 576-3322',
    address: '600 Gain Court, Riviera, Alaska, 8948',
    about:
      'Id nostrud tempor deserunt occaecat. Labore commodo culpa dolor nostrud qui ipsum dolore sit minim in occaecat. Dolore non pariatur labore qui qui duis excepteur irure irure. Voluptate aliquip elit est sit mollit eiusmod consequat labore eiusmod do.\r\n',
    registered: '2022-04-04T04:04:21 -06:00',
    latitude: -18.361254,
    longitude: 19.597255,
    tags: ['aute', 'est', 'incididunt', 'cillum', 'officia', 'sint', 'aute'],
    friends: [
      {
        id: 0,
        name: 'Abigail Leblanc',
      },
      {
        id: 1,
        name: 'Jordan Maldonado',
      },
      {
        id: 2,
        name: 'Hunter Hays',
      },
    ],
    greeting: 'Hello, Drake Stanley! You have 10 unread messages.',
    favoriteFruit: 'strawberry',
  },
  {
    _id: '66047819835e3ff117437770',
    index: 2,
    guid: '1f749ba7-ef1e-470b-b562-b031d5a5d25b',
    isActive: false,
    balance: '$3,069.07',
    picture: 'http://placehold.it/32x32',
    age: 31,
    eyeColor: 'blue',
    name: 'Emily Woodward',
    gender: 'female',
    company: 'ZENOLUX',
    email: 'emilywoodward@zenolux.com',
    phone: '+1 (984) 404-2942',
    address: '906 National Drive, Edmund, North Dakota, 9022',
    about:
      'Nulla deserunt sunt labore eiusmod in adipisicing ullamco enim Lorem elit culpa dolore et amet. Ea dolore et velit cupidatat excepteur ut reprehenderit cillum. Anim laboris veniam laboris ullamco culpa laboris deserunt ut consectetur incididunt nulla. Aliqua excepteur fugiat minim voluptate reprehenderit laboris duis nulla incididunt occaecat quis id. Tempor sunt proident aliqua dolore. Sunt proident nisi enim aliquip tempor ex. Eiusmod ea quis laborum pariatur cillum ullamco consectetur cupidatat laborum nulla.\r\n',
    registered: '2016-07-26T05:28:02 -06:00',
    latitude: 13.272823,
    longitude: -64.782365,
    tags: ['fugiat', 'veniam', 'officia', 'cillum', 'ea', 'tempor', 'labore'],
    friends: [
      {
        id: 0,
        name: 'Bernadine Cantrell',
      },
      {
        id: 1,
        name: 'Barry Pacheco',
      },
      {
        id: 2,
        name: 'Araceli Willis',
      },
    ],
    greeting: 'Hello, Emily Woodward! You have 10 unread messages.',
    favoriteFruit: 'strawberry',
  },
  {
    _id: '66047819f3da8d6664b3ece0',
    index: 3,
    guid: '4555ae4e-7a51-4c4a-94f2-d40c3bf2e2f7',
    isActive: false,
    balance: '$1,566.10',
    picture: 'http://placehold.it/32x32',
    age: 24,
    eyeColor: 'blue',
    name: 'Malinda Bridges',
    gender: 'female',
    company: 'DAYCORE',
    email: 'malindabridges@daycore.com',
    phone: '+1 (808) 596-3748',
    address: '669 Harway Avenue, Gratton, Utah, 7839',
    about:
      'Exercitation id irure velit nostrud eiusmod proident ullamco incididunt Lorem adipisicing laborum ut. Ea ipsum dolor non qui laboris veniam quis. Tempor reprehenderit duis duis nostrud reprehenderit exercitation dolore. Voluptate est velit esse reprehenderit. Laborum nisi incididunt excepteur fugiat magna incididunt nulla excepteur aute voluptate.\r\n',
    registered: '2014-02-19T04:00:32 -06:00',
    latitude: -14.777694,
    longitude: -6.513731,
    tags: ['ut', 'fugiat', 'non', 'nulla', 'fugiat', 'ad', 'magna'],
    friends: [
      {
        id: 0,
        name: 'Kent Hampton',
      },
      {
        id: 1,
        name: 'Liz Gillespie',
      },
      {
        id: 2,
        name: 'Vivian Fowler',
      },
    ],
    greeting: 'Hello, Malinda Bridges! You have 2 unread messages.',
    favoriteFruit: 'banana',
  },
  {
    _id: '660478192bcb211360b50d3c',
    index: 4,
    guid: 'dfc17da9-6f31-458b-89d2-1b0f1b855db0',
    isActive: false,
    balance: '$1,577.03',
    picture: 'http://placehold.it/32x32',
    age: 37,
    eyeColor: 'blue',
    name: 'Bernadette George',
    gender: 'female',
    company: 'MAGNAFONE',
    email: 'bernadettegeorge@magnafone.com',
    phone: '+1 (846) 492-2679',
    address: '585 Dakota Place, Jennings, Montana, 6510',
    about:
      'Non consequat eiusmod eu nulla occaecat sint. Amet anim in magna cillum esse aliquip quis consectetur quis voluptate in ut in duis. Aliquip anim exercitation officia commodo officia in.\r\n',
    registered: '2022-05-12T03:47:31 -06:00',
    latitude: 20.777374,
    longitude: 55.672742,
    tags: ['ipsum', 'qui', 'mollit', 'non', 'commodo', 'est', 'proident'],
    friends: [
      {
        id: 0,
        name: 'Holman Terry',
      },
      {
        id: 1,
        name: 'Shelton Solomon',
      },
      {
        id: 2,
        name: 'Minnie Whitehead',
      },
    ],
    greeting: 'Hello, Bernadette George! You have 10 unread messages.',
    favoriteFruit: 'banana',
  },
];
